language: ruby
rvm:
- 2.2
script:
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --disable-external
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_7bbee2d42c21_key -iv $encrypted_7bbee2d42c21_iv
  -in deploy-key.enc -out deploy-key -d
