# Site
title: Ahmad Assaf's Blog
description: Ahmad Assaf's blog about Software Engineering, Data Science, Productivity and Web Development
url: http://127.0.0.1:4000
logo: logo.svg
locale: en_US

background:
  homepage: images/home.png             # this image will be shown on homepage's left block
  default-post: images/logo-plain.png   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
google-analytics: UA-11075253-1

# Social Links
#email:             email
#google.plus:        username
twitter:            username
#facebook:           username
github:             username
stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
behance:           username

featured: []

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    tag: '/:name/'
    category: '/:name/'

# posts-list pagination
paginate: 7
paginate_path: "blog/page/:num"

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-archives
  - jekyll-paginate

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store, node_modules]